name: Build

on: push

jobs:
    build:
      runs-on: ubuntu-latest 
      name: Build
      steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Build it
        run: |
           npm run lit
           npm run build
      - name: Commit & Push changes
        uses: actions-js/push@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
        
      
        
